### ISSUE TITLE
Cannot make it works under Dart 1.9.1

### ISSUE THREAD

**Issue by invada** [luisvt/aha_table_dart#1]
Hi! I would love to use your Dart import of aha-table but it does not seems to work under Dart 1.9.1

I have the following error message: Breaking on exception: Class 'TableElement' has no instance method 'removeAttribute'.

Could you help me?

Thanks a lot

**Comment by luisvt** [comment]
Sorry, there are many things that I haven't change from javascript. Instead `removeAttribute` should be `attributes.remove`

**Comment by luisvt** [comment]
it is partially working. You can test it.

**Comment by invada** [comment]
Thanks a lot :) I will try to use it in a personal project.
